#!/bin/bash
 
# gitflow简化版指令集
# 比如git flow feature start <name>，可以换成脚本执行./gitflow -fs <name>。

type=""
# start publish finish
action=""
# branch
branch="$2"

while [ -n "$1" ]; do # while loop starts
    case "$1" in
 
    -a) echo "-a option passed" ;;
 	
 	# feature all
    -fs) 
        type="feature"
        action="start"
        shift
        ;;
    -fp) 
        type="feature"
        action="publish"
        shift
        ;;
    -ff) 
        type="feature"
        action="finish"
        shift
        ;;
    # feature all
    -rs) 
        type="release"
        action="start"
        shift
        ;;
    -rp) 
        type="release"
        action="publish"
        shift
        ;;
    -rf) 
        type="release"
        action="finish"
        shift
        ;;
    -hs) 
        type="hotfix"
        action="start"
        shift
        ;;
    -hf) 
        type="hotfix"
        action="finish"
        shift
        ;;
	# release all
    *) echo "Option $1 not recognized" ;;

    esac
 
    shift
 
done
echo "git flow preparing action:$action type: $type branch $branch"

git flow $type $action $branch
